### ISSUE TITLE
Efficientnet-lite Backbone

### ISSUE THREAD

**Issue by VicariNishimura** [google/automl#357]
Hello,
I'm having trouble using efficientnet-lite backbone as it seems impossible to load weights from the efficientnet official repo (http://storage.googleapis.com/cloud-tpu-checkpoints/efficientnet/lite/{backbone_name}.tar.gz)

I got the following error each time (and for every layer):

skip efficientnet-lite1/model/stem/conv2d/kernel (efficientnet-lite1/model/stem/conv2d/kernel) -- not in ckpt

Is there any solution to use it ?

**Comment by mingxingtan** [comment]
Hi @VicariNishimura , your issue should have been fixed. (I forgot to update lite backbone builder in the previous code refactoring).

**Comment by VicariNishimura** [comment]
No, it is now easier to build them (thanks), but still can't use pretrain imagenet, maybe i'm doing something wrong, have you tried to use it in a "Train Pascal VOC 2012 from ImageNet checkpoint for Backbone." cas ?

**Comment by VicariNishimura** [comment]
I got it running, perform badly but I may update on this after some try, thanks.
